### ISSUE TITLE
View does not render in HorizontalScrollView

### ISSUE THREAD

**Issue by RadicalMonkey** [ManuelPeinado/ImageLayout#1]
Hi,

Thanks for this great library! 

I'm having an issue when placing this view inside a horizontalscrollview. The view doesn't render at all. Is there a way to get this to work? Your code is beyond my level of expertise otherwise I would have tried to resolve it.

Thanks

**Comment by ManuelPeinado** [comment]
Hi, thanks for using the library.

I've added a small sample that shows how HorizontalScrollView can be used successfully with ImageLayout:

https://github.com/ManuelPeinado/ImageLayout/blob/master/sample/src/com/manuelpeinado/imagelayout/demo/HorizontalScrollViewActivity.java

I hope this will solve your problem, let me know if it doesn't.

**Comment by RadicalMonkey** [comment]
Thanks works great! Cant believe I didnt try the match_parent on the scrollview!
